#!/usr/bin/env python3.8

import argparse
import logging
import sys

import tables
import tqdm

from FeatureExtractor import FeatureExtractor
from utils import open_output

logger = logging.getLogger(__name__)

parser = argparse.ArgumentParser()
parser.add_argument('input', metavar='INFILE', type=str,
    help='tsv file to be processed (generated by tshark based on input pcap)')
parser.add_argument('-o', '--output', metavar='OUTFILE', type=str, required=True,
    help='h5 file to be generated (containing extracted features)')
parser.add_argument('-l', '--log-level', type=str, default='info',
    help='logging level (error, info, debug, ...)')
parser.add_argument('-n', '--packet-limit', type=int, default=sys.maxsize,
    help='the number of packets to process')
parser.add_argument('-L', '--lambdas', type=float, nargs="+", default=[5, 3, 1, .1, .01],
    help='list of kitsune lambdas, default ')

args = parser.parse_args()

# Set logging level
logging.basicConfig(level=args.log_level.upper())

# Create feature extractor (AfterImage)
extractor = FeatureExtractor(args.input, args.packet_limit, args.lambdas)
features_count = extractor.get_num_features()

logger.info("running extractor")

atom = tables.Float64Atom()
with tables.open_file(args.output, mode='w') as outfile:
    farray = outfile.create_earray(outfile.root, 'data', atom, (0, features_count))

    for vector in tqdm.tqdm(extractor):
        farray.append(vector.reshape(1, features_count))

logger.info("extractor finished")
